### ISSUE TITLE
error when import commponent 

### ISSUE THREAD

**Issue by HolyGamesCode** [sb89/facebook-login-react-component#2]
When I try to import the component I get this error 

Could not find a declaration file for module 'facebook-login-react' {my node modules } implicitly has an 'any' type.
  Try `npm i --save-dev @types/facebook-login-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'facebook-login-react';`ts

I'm using typescript 4.3.5 and react 17.0.2

**Comment by HolyGamesCode** [comment]
same issue when import { FacebookLoginWithButton } from 'facebook-login-react';

**Comment by sb89** [comment]
I've managed to install this and haven't encountered the issuers above. Closing this just now but will re-open if people are still having issues.

**Comment by sb89** [comment]
https://github.com/sb89/facebook-login-react-component/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted
